name: build-and-release

inputs:
  tag:
    description: 'The tag to release'
    required: true
  token:
    description: 'The GitHub token'
    required: true
  gpg_private_key:
    description: 'The GPG private key'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install DKMS
      run: sudo apt-get install -y debhelper devscripts dh-exec dkms dpkg
      shell: bash

    - name: Build Debian package
      run: dkms mkdeb --source-only
      shell: bash

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: |
          ../*.deb
        token: ${{ inputs.token }}
        tag_name: ${{ inputs.tag }}

    # build personal apt repository
    - name: import gpg key
      run: |
        echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --import
      shell: bash
      env:
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}

    - name: Build APT repository
      run: |
        ./build_apt_pages.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Publish artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

    - name: Deploy pages
      uses: actions/deploy-pages@v4
